# Generated by Django 4.0.1 on 2022-01-18 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_commentbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentbook',
            old_name='user',
            new_name='owner',
        ),
    ]
